Adding parallel_each functions. Adding the execution_space as an argument for the for_each/parallel_each functions
CExA-project/ddc pull request #288
Opened 2024-02-14 10:54 UTC by thierryantoun

2024-02-14 14:09 UTC, tpadioleau reviewed
I would advise to keep `ddc::for_each(dom, f)` and replace all previous `ddc::for_each(ddc::policies::parallel_device, dom, f);` by `ddc::parallel_for_each(dom, f);`

2024-02-16 14:53 UTC, tpadioleau requested changes
Almost ready, no need to have a `if constexpr`, if `ExecSpace` is `Kokkos::Serial` then the `parallel_for_each` will handle it fine.

2024-02-16 14:53 UTC, tpadioleau commented on include/ddc/for_each.hpp
> +/** iterates over a nD domain using the default execution policy
```suggestion
/** iterates over a nD domain in serial
```

2024-02-16 14:53 UTC, tpadioleau commented on include/ddc/for_each.hpp
> +/** iterates over a nD domain using the serial execution policy
```suggestion
/** iterates over a nD domain using a given `Kokkos` execution space
```

2024-02-16 14:53 UTC, tpadioleau commented on include/ddc/for_each.hpp
> +            ExecSpace>(std::forward<ExecSpace>(execution_space), domain, std::forward<Functor>(f));
```suggestion
    detail::for_each_kokkos(std::forward<ExecSpace>(execution_space), domain, std::forward<Functor>(f));
```

2024-02-16 14:53 UTC, tpadioleau commented on include/ddc/for_each.hpp
>   */
```suggestion
/** iterates over a nD domain using the `Kokkos` default execution space
 * @param[in] domain the domain over which to iterate
 * @param[in] f      a functor taking an index as parameter
 */
```

2024-02-16 14:53 UTC, tpadioleau commented on include/ddc/for_each.hpp
> +            std::forward<Functor>(f));
```suggestion
    parallel_for_each(
            Kokkos::DefaultExecutionSpace(),
            domain,
            std::forward<Functor>(f));
```

2024-02-16 14:53 UTC, tpadioleau commented on include/ddc/kernels/splines/spline_builder.hpp
> +        }
You can also apply this to all the rest
```suggestion
            ddc::parallel_for_each(
                    exec_space(),
                    batch_domain(),
                    KOKKOS_LAMBDA(typename batch_domain_type::discrete_element_type j) {
                        for (int i = s_nbc_xmin; i > 0; --i) {
                            spline(ddc::DiscreteElement<bsplines_type>(s_nbc_xmin - i), j)
                                    = derivs_xmin_values(ddc::DiscreteElement<deriv_type>(i), j)
                                      * ddc::detail::ipow(dx_proxy, i + s_odd - 1);
                        }
                    });
```

2024-02-16 14:53 UTC, tpadioleau commented on tests/for_each.cpp
> +            [=](DElem0D const i) { view(i) += 1; });
```suggestion
    ddc::parallel_for_each(
            Kokkos::DefaultHostExecutionSpace(),
            dom,
            [=](DElem0D const i) { view(i) += 1; });
```

2024-02-16 14:53 UTC, tpadioleau commented on tests/for_each.cpp
> +            [=](DElemX const ix) { view(ix) += 1; });
```suggestion
    ddc::parallel_for_each(
            Kokkos::DefaultHostExecutionSpace(),
            dom,
            [=](DElemX const ix) { view(ix) += 1; });
```

2024-02-16 14:53 UTC, tpadioleau commented on tests/for_each.cpp
> +            [=](DElemXY const ixy) { view(ixy) += 1; });
```suggestion
    ddc::parallel_for_each(
            Kokkos::DefaultHostExecutionSpace(),
            dom,
            [=](DElemXY const ixy) { view(ixy) += 1; });
```

2024-02-16 15:05 UTC, thierryantoun commented
But if the **parallel_for_each** function works fine with **Kokkos::Serial** as an execution space, why is the simple **for_each** function still needed?

2024-02-16 15:18 UTC, tpadioleau commented
> But if the **parallel_for_each** function works fine with **Kokkos::Serial** as an execution space, why is the simple **for_each** function still needed?

One cannot call `Kokkos::parallel_for` with `Kokkos::Serial` inside a `Kokkos::parallel_for` with `Kokkos::Cuda`, we plan to support that with `ddc::for_each`. An other reason is that, `Kokkos::Serial` may not always be available depending on the compilation options. Only `Kokkos::DefaultHostExecutionSpace` and `Kokkos::DefaultExecutionSpace` are always available. This is linked to #225.

2024-02-19 13:03 UTC, tpadioleau approved these changes

2024-02-19 16:50 UTC, merged